# Generated by Django 5.1 on 2024-09-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventdiscussiontopic_eventdiscussioncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
