# Generated by Django 5.1 on 2024-09-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
